[package]
name = "day-08-wasteland"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
prime_factorization = "1.0.4"
rayon = "1.8.0"
