[package]
name = "day-25-wires"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphrs = "0.7.0"
itertools = "0.12.0"
petgraph = "0.6.4"
rayon = "1.8.0"
